apiVersion: v1
kind: Pod
metadata:
  name: toleratedpod1
spec:
  containers:
  - name: toleratedcntr1
    image: nginx:1.16-alpine
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "web"
    effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: toleratedpod2
spec:
  containers:
  - name: toleratedcntr2
    image: nginx:1.16-alpine
  tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"
