apiVersion: v1
kind: Pod
metadata:
  name: podvolumeemptyDir
spec:
  containers:
  - name: app
    image: busybox
    args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)" >> /cache/1.log ; i=$((i+1)); sleep 1; done']
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: /cache
  - name: log
    image: busybox
    args: [/bin/sh, -c, 'tail -n+1 -f /cache/1.log']
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: /cache
  volumes:
  - name: ephemeral
    emptyDir: {}
